services:
  mongo:
    image: mongo:5.0
    container_name: graylog-mongo
    restart: always
    networks:
      - graylog-network
    volumes:
      - mongo_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: graylog-opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - graylog-network
    volumes:
      - os_data:/usr/share/opensearch/data

  graylog:
    image: graylog/graylog:5.2
    container_name: graylog-server
    depends_on:
      - mongo
      - opensearch
    restart: always
    env_file:
      - .env
    environment:
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "${GRAYLOG_HTTP_EXTERNAL_URI:-http://localhost:9000/}"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongo:27017/graylog"
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    networks:
      - graylog-network
    ports:
      - "9000:9000"
      - "1514:1514/tcp"
      - "1514:1514/udp"
      - "12201:12201/tcp"
      - "12201:12201/udp"
      - "5555:5555/tcp"
      - "5555:5555/udp"
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/data/journal

networks:
  graylog-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  os_data:
    driver: local
  graylog_data:
    driver: local
  graylog_journal:
    driver: local
